# A default Taskfile.yml for Create Go App project.
# Author: Vic Shóstak <truewebartisans@gmail.com> (https://1wa.co)

version: "2"

tasks:
  # Default task
  default:
    cmds:
      - task: frontend-run
      - task: backend-run

  # Backend tasks
  backend-test:
    dir: ./backend
    cmds:
      - task test
  backend-run:
    dir: ./backend
    cmds:
      - task run
  backend-build:
    dir: ./backend
    cmds:
      - task build

  # Frontend tasks
  frontend-test:
    dir: ./frontend
    cmds:
      - npm run test
  frontend-run:
    dir: ./frontend
    cmds:
      - npm start
  frontend-build:
    dir: ./frontend
    cmds:
      - npm run build
