version: "2"

vars:
  APP: apiserver{{exeExt}}

tasks:
  default:
    cmds:
      - task: run

  clean:
    desc: Clean project
    cmds:
      - rm -rf ./build

  test:
    desc: Test project
    cmds:
      - go test -cover ./...

  security:
    desc: Run gosec for project
    cmds:
      - gosec -quiet ./...

  build:
    desc: Build the API server
    cmds:
      - mkdir ./build
      - CGO_ENABLED=0 GOARCH=amd64 go build -ldflags="-w -s" -o ./build/{{.APP}} .

  run:
    desc: Build and run the API server
    cmds:
      - task: clean
      - task: security
      - task: test
      - task: build
      - ./build/{{.APP}}
