# Server config
server:
  host: 0.0.0.0 # if you want to run this API server from a Docker container, set it to 0.0.0.0
  port: 5000

# Database config
database:
  host: 127.0.0.1
  port: 5432
  username: postgres
  password: 1234

# Static files config
static:
  prefix: /
  path: ./static
